"use client";
import { useState } from "react";
import Link from "next/link";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";

export default function LoginPage() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); setError(""); const { error: authError } = await createSupabaseBrowserClient().auth.signInWithPassword({ email, password }); setLoading(false); if (authError) setError("เข้าสู่ระบบไม่สำเร็จ กรุณาตรวจสอบอีเมลและรหัสผ่าน"); else window.location.href = "/interview-queue"; }
  return <main className="min-h-screen grid place-items-center p-6 bg-emerald-950"><form onSubmit={submit} className="w-full max-w-sm rounded-2xl bg-white p-8 shadow-xl"><p className="text-sm font-semibold text-emerald-700">COM7 Recruitment</p><h1 className="mt-1 text-2xl font-bold">เข้าสู่ระบบผู้ดูแล</h1><p className="mt-2 text-sm text-slate-500">Interview Queue Management System</p><label className="mt-6 block text-sm font-medium">อีเมล<input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 outline-emerald-600" /></label><label className="mt-4 block text-sm font-medium">รหัสผ่าน<input required type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 outline-emerald-600" /></label><div className="mt-2 text-right"><Link href="/forgot-password" className="text-xs font-medium text-emerald-700 underline">ลืมรหัสผ่าน?</Link></div>{error && <p className="mt-3 text-sm text-red-600">{error}</p>}<button disabled={loading} className="mt-6 w-full rounded-xl bg-emerald-700 py-3 font-semibold text-white disabled:bg-slate-300">{loading ? "กำลังเข้าสู่ระบบ..." : "เข้าสู่ระบบ"}</button><p className="mt-4 text-center text-sm text-slate-500">ยังไม่มีบัญชี? <Link href="/signup" className="font-semibold text-emerald-700 underline">สมัครสมาชิก</Link></p></form></main>;
}